MCU = RP2040
BOOTLOADER = rp2040
LTO_ENABLE = yes

VIA_ENABLE = yes

EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

DYNAMIC_KEYMAP_MACRO_ENABLE = yes
MACRO_ENABLE = yes

#--------------oled------------
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OPT_DEFS += -DHAL_USE_I2C=TRUE